Следующая проблема

class Vector:
    
    def __init__(self, *args):
        self.values = list(args)
        
    def __repr__(self):
        return str(self.values)
    
Создадим некий вектор

v1 = Vector(1,2,3,4,5)
print(v1) # [1, 2, 3, 4, 5]

Всё как и должно быть
но теперь мы хотим обратиться к какому-то конретному элементу, например по индексу 1
будь это обычный списко мы бы просто сделали так
print(v[1]) # получим ошибку
так как это уже не список а наш класс
мы можем сделать так
print(v1.values[1]) # 2
Всё окей получили результат, но допустим мы хотим обратиться как к обычному списку
поможет __getitem__

class Vector:

    def __init__(self, *args):
        self.values = list(args)

    def __repr__(self):
        return str(self.values)

    def __getitem__(self, item): # в переменную item будет поступать наш индекс
        if 0 <= item < len(self.values): # проверяем не вышли ли за границы массива
            return self.values[item] 
        else:
            raise IndexError('Индекс за границами нашей коллекции')

и теперь
v1 = Vector(1,2,3,4,5)
print(v1)
print(v1[0])

# Вывод
[1, 2, 3, 4, 5]
1
#
Сработало!

А теперь мы хотим не только выводить это значение, а ещё и записывать туда что-то как в обычном списке
например
v1[1] = 50
# будет ошибка

Для этого есть метод __setitem__

Дополним наш тот класс этим методом

    def __setitem__(self, key, value): # key - индекс который хотим изменить, value - значение на которое
					# поменять
        if 0 <= key < len(self.values):
            self.values[key] = value
        else:
            raise IndexError('Индекс за границами нашей коллекции')

В итоге

v1 = Vector(1,2,3,4,5)
print(v1[0])
v1[0] = 50
print(v1[0], v1)

# Вывод
1
50 [50, 2, 3, 4, 5]
#

Работает!

А теперь перейдём к методу delitem
del v1[0] # Снова ошибка

Делаем delitem

    def __delitem__(self, key):
        if 0 <= key < len(self.values):
            del self.values[key]
        else:
            raise IndexError('Индекс за границами нашей коллекции')

v1 = Vector(1,2,3,4,5)
print(v1[0])
del v1[0]
print(v1)

# Вывод
1
[2, 3, 4, 5]
#

Удалилось, всё работает















